import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import Header from "./component/layout/Header";
import { getCurrentSession } from "./actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "./component/layout/HeaderCategorySelector";


const inter  = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {user} =await getCurrentSession()

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased `}
      >
        <Header user={user} categorySelector={<HeaderCategorySelector/>}/>
        {children}
        <SanityLive/>
      </body>
    </html>
  );
}
